services:
  web1:
    image: httpd:2.4
    ports:
      - 81:80
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs

  web2:
    image: httpd:2.4
    ports:
      - 82:80
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
