# https://medium.com/@a_farag/deploying-a-node-js-project-with-docker-and-nginx-1bb5a05bc439
# 
version: '3.8'

services:
  node-app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
    depends_on:
      - node-app
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge